baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ayan Abdullahi'
theme = "paper"

[params]
  disableHLJS = true                         # don't use highlight.js
  twitter = 'YOUR_TWITTER_ID'                
#  github = 'YOUR_GITHUB_ID'                  
  instagram = 'YOUR_INSTAGRAM_ID'            